# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-base"

  config.vm.define "ubuntu-box" do |box|

    box.vm.provision "shell",  inline: "bash /vagrant/setup.sh", privileged: false
  
    box.vm.provider :virtualbox do |vb|
      vb.name = "ubuntu-box-base"
      vb.memory = 4096
      vb.cpus = 2
    end  
  end
end
