# -*- mode: ruby -*-
# vi: set ft=ruby :

include_vagrantfile = "../base.ubuntu.Vagrantfile"
load include_vagrantfile if File.exist?(include_vagrantfile)

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # config.vm.provision  "===> Installing default packages", type: 'shell' do |shell|
  #   shell.path = File.expand_path("./scripts/init")
  # end

  config.vm.provision "===> Installing ansible", type: "shell" do |shell|
    shell.path = File.expand_path("../scripts/ansible/ansible")
  end

  config.vm.provision "===> Cleaning up after packages installation", type: "shell" do |shell|
    shell.path = File.expand_path("../scripts/cleanup/cleanup.sh")
  end

  config.vm.provision "===> Optimizing space", type: "shell" do |shell|
    shell.path = File.expand_path("../scripts/cleanup/minimize.sh")
  end

end
